CREATE TABLE PRODUCTS (
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	PRODUCT_NAME VARCHAR(255) NOT NULL,
	PRODUCT_DESCRIPTION VARCHAR(512) NOT NULL,
	);

INSERT INTO PRODUCTS (PRODUCT_NAME, PRODUCT_DESCRIPTION)
VALUES
('BOOK', 'JAVA HOW TO PROGRAM'),
('LAPTOP', 'DELL XPS TOWER I7'),
('KEYBOARD', 'DELL SOFTTOUCH WITH MOUSE')